spring:
  application:
    name: adminservice
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
encrypt:
  key: secret