server:
  port: 8181
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/strr_admin?serverTimezone=UTC
    username: root
    password: '{cipher}b508a19f5f714b97916c70bd872da77208e5dca3da9830fefe9a1a50f683de9c'
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    # 下划线驼峰映射
    map-underscore-to-camel-case: true
springdoc:
  packagesToScan: com.strr
  swagger-ui:
    enabled: true
oauth2:
  web: http://localhost:8080