server:
  port: 8000
spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay
  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: spring
            client-id: STRR_CLIENT
            client-secret: STRR_SECRET
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid, web
            client-name: Spring
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
# web
url:
  web: http://127.0.0.1:8080